language: ruby
rvm:
- 2.1.0
- 2.2.0
- 2.3.0

gemfile:
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

sudo: false
cache: bundler

notifications:
  hipchat:
    rooms:
      secure: HD93T2k0sXQYPk/SLwROvvbQmMDqOxxdgd3eKhocYmH/nKcU/+p3xIls1qstnUh+G4kVwj2ZhWkYg7lfg4rmDfO7RlKWA9zTX3Aaed4cSF/Od54S1Dqwl12KGSITs/nrY2W5zQ+JJ5chFKRYuiRpqb4cPQeafJojccHdaYjYShM=
    template:
      - '@all %{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
